version: '3.8'

services:
  app:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - FXTWITTER_API_URL=https://api.fxtwitter.com
    volumes:
      - .:/app
    restart: always
  